name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        id: build-push
        with:
          push: true
          file: ./Traefik.Middelware.Api/Dockerfile
          tags: jfuerlinger/traefik-middlewares:latest
          platforms: linux/amd64,linux/arm64
          outputs: |
            imageDigest: ${{ steps.build-push.outputs.digest }}

      - name: Tag and Push platform specific images
        if: steps.build-push.outputs.imageDigest
        run: |
          docker tag jfuerlinger/traefik-middlewares:latest jfuerlinger/traefik-middlewares:linux-amd64
          docker tag jfuerlinger/traefik-middlewares:latest jfuerlinger/traefik-middlewares:linux-arm64
          docker push jfuerlinger/traefik-middlewares:linux-amd64
          docker push jfuerlinger/traefik-middlewares:linux-arm64