name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Verify QEMU
        run: |
          docker run --rm --platform linux/arm64 alpine uname -m

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push for amd64
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./Traefik.Middelware.Api/Dockerfile
          tags: jfuerlinger/traefik-middlewares:amd64-latest
          platforms: linux/amd64

      - name: Build and push for arm64
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./Traefik.Middelware.Api/Dockerfile
          tags: jfuerlinger/traefik-middlewares:arm64-latest
          platforms: linux/arm64

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./Traefik.Middelware.Api/Dockerfile
          tags: jfuerlinger/traefik-middlewares:latest
          platforms: linux/amd64,linux/arm64
